# Dockerfile.postgresql
FROM postgres:16

# Set up environment variables for user and password
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=123456

# Install PostGIS packages for PostgreSQL 16
RUN apt-get update \
    && apt-get install -y postgis postgresql-16-postgis-3 \
    && rm -rf /var/lib/apt/lists/*

# Copy the initialization script to the entrypoint directory
COPY docker/postgresql/init-databases_postgresql.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init-databases_postgresql.sh
