dialects:
  - postgres

default:
  dialect: postgres
  benchmark_scale: scale
  sql_mode: patch
  response_field: prediction
  input_dir: data/benchmark/effi-sql
  benchmark_file: data/benchmark/effi-sql/eff-sql-pg.jsonl
  output_dir: outputs/postgres

docker:
  small_db_compose: docker/compose/smalldb.yml
  tpch_compose: docker/compose/tpch.yml
  eval_container: so_eval_env
