services:
  postgresql_small:
    build:
      context: ../..
      dockerfile: Dockerfile.postgresql
    container_name: postgresql_small
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DUMP_VARIANT: "${POSTGRES_DUMP_VARIANT:-scale}"
      TZ: "Asia/Shanghai"
    command:
      - "-c"
      - "max_connections=300"
      - "-c"
      - "shared_buffers=256MB"
    ports:
      - "7001:5432"
    volumes:
      - postgresql_small_data:/var/lib/postgresql/data
      - ../../data/databases/bird-interact-scale/table-dumps:/docker-entrypoint-initdb.d/postgre_scale_table_dumps
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 20

  so_eval_env:
    build:
      context: ../..
      dockerfile: Dockerfile.so_eval
    container_name: so_eval_env
    volumes:
      - ../../:/workspace/
    command: ["tail", "-f", "/dev/null"]

volumes:
  postgresql_small_data:
